version: '3'
services:
  nginx:
    image: nginx:latest
    container_name: nginx-file-server
    ports:
      - "8080:80"
    volumes:
      - /data:/usr/share/nginx/html:z
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80
    command: /bin/sh -c "nginx -g 'daemon off;'"
